<?xml version="1.0" encoding="utf-8"?><Database Name="dmaj0917_1067643" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=kraka.ucn.dk;Initial Catalog=dmaj0917_1067643;User ID=dmaj0917_1067643" SettingsObjectName="DeliveryServiceLibrary.Properties.Settings" SettingsPropertyName="dmaj0917_1067643ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccountType" Member="AccountTypes">
    <Type Name="AccountType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="AccountType_User" Member="Users" ThisKey="ID" OtherKey="AccountTypeID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.VouchersUsed" Member="VouchersUseds">
    <Type Name="VouchersUsed">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VoucherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Voucher_VouchersUsed" Member="Voucher" ThisKey="VoucherID" OtherKey="ID" Type="Voucher" IsForeignKey="true" />
      <Association Name="User_VouchersUsed" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Voucher" Member="Vouchers">
    <Type Name="Voucher">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Voucher_VouchersUsed" Member="VouchersUseds" ThisKey="ID" OtherKey="VoucherID" Type="VouchersUsed" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PassSalt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_VouchersUsed" Member="VouchersUseds" ThisKey="ID" OtherKey="UserID" Type="VouchersUsed" />
      <Association Name="User_Package" Member="Packages" ThisKey="ID" OtherKey="CourierID" Type="Package" />
      <Association Name="User_Package1" Member="Packages1" ThisKey="ID" OtherKey="SenderID" Type="Package" />
      <Association Name="AccountType_User" Member="AccountType" ThisKey="AccountTypeID" OtherKey="ID" Type="AccountType" IsForeignKey="true" />
      <Association Name="Person_User" Member="Person" ThisKey="PersonID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusString" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Status_Package" Member="Packages" ThisKey="ID" OtherKey="StatusID" Type="Package" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cpr" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Person_User" Member="Users" ThisKey="ID" OtherKey="PersonID" Type="User" />
      <Association Name="Person_Application" Member="Applications" ThisKey="ID" OtherKey="PersonID" Type="Application" />
    </Type>
  </Table>
  <Table Name="dbo.Package" Member="Packages">
    <Type Name="Package">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Width" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Barcode" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ReceiverFirstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ReceiverLastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ToAddress" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FromAddress" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ReceiverPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Package_DeliveryDate" Member="DeliveryDates" ThisKey="ID" OtherKey="PackageID" Type="DeliveryDate" />
      <Association Name="Package_Delivery" Member="Deliveries" ThisKey="ID" OtherKey="PackageID" Type="Delivery" />
      <Association Name="User_Package" Member="User" ThisKey="CourierID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="User_Package1" Member="User1" ThisKey="SenderID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="Status_Package" Member="Status" ThisKey="StatusID" OtherKey="ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryDate" Member="DeliveryDates">
    <Type Name="DeliveryDate">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeToPickUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PickedUpTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliverTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Package_DeliveryDate" Member="Package" ThisKey="PackageID" OtherKey="ID" Type="Package" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Delivery" Member="Deliveries">
    <Type Name="Delivery">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Package_Delivery" Member="Package" ThisKey="PackageID" OtherKey="ID" Type="Package" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Applications">
    <Type Name="Application">
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CVPath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IDPicturePath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="YellowCardPath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="guid" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Association Name="Person_Application" Member="Person" ThisKey="PersonID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
</Database>