//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientMVC.Tests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISenderService")]
    public interface ISenderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddSender", ReplyAction="http://tempuri.org/ISenderService/AddSenderResponse")]
        int AddSender(WebClientMVC.SenderServiceReference1.SenderResource sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddSender", ReplyAction="http://tempuri.org/ISenderService/AddSenderResponse")]
        System.Threading.Tasks.Task<int> AddSenderAsync(WebClientMVC.SenderServiceReference1.SenderResource sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllUsers", ReplyAction="http://tempuri.org/ISenderService/GetAllUsersResponse")]
        WebClientMVC.SenderServiceReference1.SenderResource[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllUsers", ReplyAction="http://tempuri.org/ISenderService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.SenderResource[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddApplication", ReplyAction="http://tempuri.org/ISenderService/AddApplicationResponse")]
        int AddApplication(WebClientMVC.SenderServiceReference1.ApplicationResource application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddApplication", ReplyAction="http://tempuri.org/ISenderService/AddApplicationResponse")]
        System.Threading.Tasks.Task<int> AddApplicationAsync(WebClientMVC.SenderServiceReference1.ApplicationResource application);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllApplications", ReplyAction="http://tempuri.org/ISenderService/GetAllApplicationsResponse")]
        WebClientMVC.SenderServiceReference1.ApplicationResource[] GetAllApplications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllApplications", ReplyAction="http://tempuri.org/ISenderService/GetAllApplicationsResponse")]
        System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.ApplicationResource[]> GetAllApplicationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddCourier", ReplyAction="http://tempuri.org/ISenderService/AddCourierResponse")]
        int AddCourier(WebClientMVC.SenderServiceReference1.SenderResource courier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddCourier", ReplyAction="http://tempuri.org/ISenderService/AddCourierResponse")]
        System.Threading.Tasks.Task<int> AddCourierAsync(WebClientMVC.SenderServiceReference1.SenderResource courier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/DeleteApplication", ReplyAction="http://tempuri.org/ISenderService/DeleteApplicationResponse")]
        int DeleteApplication(WebClientMVC.SenderServiceReference1.ApplicationResource application, bool deletePerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/DeleteApplication", ReplyAction="http://tempuri.org/ISenderService/DeleteApplicationResponse")]
        System.Threading.Tasks.Task<int> DeleteApplicationAsync(WebClientMVC.SenderServiceReference1.ApplicationResource application, bool deletePerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/ClearDB", ReplyAction="http://tempuri.org/ISenderService/ClearDBResponse")]
        void ClearDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/ClearDB", ReplyAction="http://tempuri.org/ISenderService/ClearDBResponse")]
        System.Threading.Tasks.Task ClearDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetBalanceByUsername", ReplyAction="http://tempuri.org/ISenderService/GetBalanceByUsernameResponse")]
        int GetBalanceByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetBalanceByUsername", ReplyAction="http://tempuri.org/ISenderService/GetBalanceByUsernameResponse")]
        System.Threading.Tasks.Task<int> GetBalanceByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddToBalance", ReplyAction="http://tempuri.org/ISenderService/AddToBalanceResponse")]
        void AddToBalance(string username, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddToBalance", ReplyAction="http://tempuri.org/ISenderService/AddToBalanceResponse")]
        System.Threading.Tasks.Task AddToBalanceAsync(string username, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/UseVoucher", ReplyAction="http://tempuri.org/ISenderService/UseVoucherResponse")]
        void UseVoucher(string username, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/UseVoucher", ReplyAction="http://tempuri.org/ISenderService/UseVoucherResponse")]
        System.Threading.Tasks.Task UseVoucherAsync(string username, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllVouchers", ReplyAction="http://tempuri.org/ISenderService/GetAllVouchersResponse")]
        WebClientMVC.SenderServiceReference1.VoucherResource[] GetAllVouchers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllVouchers", ReplyAction="http://tempuri.org/ISenderService/GetAllVouchersResponse")]
        System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.VoucherResource[]> GetAllVouchersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllUsedVouchers", ReplyAction="http://tempuri.org/ISenderService/GetAllUsedVouchersResponse")]
        WebClientMVC.SenderServiceReference1.VouchersUsedResource[] GetAllUsedVouchers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllUsedVouchers", ReplyAction="http://tempuri.org/ISenderService/GetAllUsedVouchersResponse")]
        System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.VouchersUsedResource[]> GetAllUsedVouchersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllPackages", ReplyAction="http://tempuri.org/ISenderService/GetAllPackagesResponse")]
        WebClientMVC.SenderServiceReference1.PackageModel[] GetAllPackages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetAllPackages", ReplyAction="http://tempuri.org/ISenderService/GetAllPackagesResponse")]
        System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.PackageModel[]> GetAllPackagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetDeliveryByPackageBarcode", ReplyAction="http://tempuri.org/ISenderService/GetDeliveryByPackageBarcodeResponse")]
        WebClientMVC.SenderServiceReference1.DeliveryModel GetDeliveryByPackageBarcode(double barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/GetDeliveryByPackageBarcode", ReplyAction="http://tempuri.org/ISenderService/GetDeliveryByPackageBarcodeResponse")]
        System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.DeliveryModel> GetDeliveryByPackageBarcodeAsync(double barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddPackage", ReplyAction="http://tempuri.org/ISenderService/AddPackageResponse")]
        int AddPackage(WebClientMVC.SenderServiceReference1.PackageModel model, string Username, WebClientMVC.SenderServiceReference1.DeliveryModel delivery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/AddPackage", ReplyAction="http://tempuri.org/ISenderService/AddPackageResponse")]
        System.Threading.Tasks.Task<int> AddPackageAsync(WebClientMVC.SenderServiceReference1.PackageModel model, string Username, WebClientMVC.SenderServiceReference1.DeliveryModel delivery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/TakePackage", ReplyAction="http://tempuri.org/ISenderService/TakePackageResponse")]
        int TakePackage(double barcode, int courierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/TakePackage", ReplyAction="http://tempuri.org/ISenderService/TakePackageResponse")]
        System.Threading.Tasks.Task<int> TakePackageAsync(double barcode, int courierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/ChangeStatus", ReplyAction="http://tempuri.org/ISenderService/ChangeStatusResponse")]
        int ChangeStatus(double barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderService/ChangeStatus", ReplyAction="http://tempuri.org/ISenderService/ChangeStatusResponse")]
        System.Threading.Tasks.Task<int> ChangeStatusAsync(double barcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISenderServiceChannel : WebClientMVC.Tests.ServiceReference1.ISenderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SenderServiceClient : System.ServiceModel.ClientBase<WebClientMVC.Tests.ServiceReference1.ISenderService>, WebClientMVC.Tests.ServiceReference1.ISenderService {
        
        public SenderServiceClient() {
        }
        
        public SenderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SenderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SenderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SenderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddSender(WebClientMVC.SenderServiceReference1.SenderResource sender) {
            return base.Channel.AddSender(sender);
        }
        
        public System.Threading.Tasks.Task<int> AddSenderAsync(WebClientMVC.SenderServiceReference1.SenderResource sender) {
            return base.Channel.AddSenderAsync(sender);
        }
        
        public WebClientMVC.SenderServiceReference1.SenderResource[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.SenderResource[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public int AddApplication(WebClientMVC.SenderServiceReference1.ApplicationResource application) {
            return base.Channel.AddApplication(application);
        }
        
        public System.Threading.Tasks.Task<int> AddApplicationAsync(WebClientMVC.SenderServiceReference1.ApplicationResource application) {
            return base.Channel.AddApplicationAsync(application);
        }
        
        public WebClientMVC.SenderServiceReference1.ApplicationResource[] GetAllApplications() {
            return base.Channel.GetAllApplications();
        }
        
        public System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.ApplicationResource[]> GetAllApplicationsAsync() {
            return base.Channel.GetAllApplicationsAsync();
        }
        
        public int AddCourier(WebClientMVC.SenderServiceReference1.SenderResource courier) {
            return base.Channel.AddCourier(courier);
        }
        
        public System.Threading.Tasks.Task<int> AddCourierAsync(WebClientMVC.SenderServiceReference1.SenderResource courier) {
            return base.Channel.AddCourierAsync(courier);
        }
        
        public int DeleteApplication(WebClientMVC.SenderServiceReference1.ApplicationResource application, bool deletePerson) {
            return base.Channel.DeleteApplication(application, deletePerson);
        }
        
        public System.Threading.Tasks.Task<int> DeleteApplicationAsync(WebClientMVC.SenderServiceReference1.ApplicationResource application, bool deletePerson) {
            return base.Channel.DeleteApplicationAsync(application, deletePerson);
        }
        
        public void ClearDB() {
            base.Channel.ClearDB();
        }
        
        public System.Threading.Tasks.Task ClearDBAsync() {
            return base.Channel.ClearDBAsync();
        }
        
        public int GetBalanceByUsername(string username) {
            return base.Channel.GetBalanceByUsername(username);
        }
        
        public System.Threading.Tasks.Task<int> GetBalanceByUsernameAsync(string username) {
            return base.Channel.GetBalanceByUsernameAsync(username);
        }
        
        public void AddToBalance(string username, int amount) {
            base.Channel.AddToBalance(username, amount);
        }
        
        public System.Threading.Tasks.Task AddToBalanceAsync(string username, int amount) {
            return base.Channel.AddToBalanceAsync(username, amount);
        }
        
        public void UseVoucher(string username, string code) {
            base.Channel.UseVoucher(username, code);
        }
        
        public System.Threading.Tasks.Task UseVoucherAsync(string username, string code) {
            return base.Channel.UseVoucherAsync(username, code);
        }
        
        public WebClientMVC.SenderServiceReference1.VoucherResource[] GetAllVouchers() {
            return base.Channel.GetAllVouchers();
        }
        
        public System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.VoucherResource[]> GetAllVouchersAsync() {
            return base.Channel.GetAllVouchersAsync();
        }
        
        public WebClientMVC.SenderServiceReference1.VouchersUsedResource[] GetAllUsedVouchers() {
            return base.Channel.GetAllUsedVouchers();
        }
        
        public System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.VouchersUsedResource[]> GetAllUsedVouchersAsync() {
            return base.Channel.GetAllUsedVouchersAsync();
        }
        
        public WebClientMVC.SenderServiceReference1.PackageModel[] GetAllPackages() {
            return base.Channel.GetAllPackages();
        }
        
        public System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.PackageModel[]> GetAllPackagesAsync() {
            return base.Channel.GetAllPackagesAsync();
        }
        
        public WebClientMVC.SenderServiceReference1.DeliveryModel GetDeliveryByPackageBarcode(double barcode) {
            return base.Channel.GetDeliveryByPackageBarcode(barcode);
        }
        
        public System.Threading.Tasks.Task<WebClientMVC.SenderServiceReference1.DeliveryModel> GetDeliveryByPackageBarcodeAsync(double barcode) {
            return base.Channel.GetDeliveryByPackageBarcodeAsync(barcode);
        }
        
        public int AddPackage(WebClientMVC.SenderServiceReference1.PackageModel model, string Username, WebClientMVC.SenderServiceReference1.DeliveryModel delivery) {
            return base.Channel.AddPackage(model, Username, delivery);
        }
        
        public System.Threading.Tasks.Task<int> AddPackageAsync(WebClientMVC.SenderServiceReference1.PackageModel model, string Username, WebClientMVC.SenderServiceReference1.DeliveryModel delivery) {
            return base.Channel.AddPackageAsync(model, Username, delivery);
        }
        
        public int TakePackage(double barcode, int courierId) {
            return base.Channel.TakePackage(barcode, courierId);
        }
        
        public System.Threading.Tasks.Task<int> TakePackageAsync(double barcode, int courierId) {
            return base.Channel.TakePackageAsync(barcode, courierId);
        }
        
        public int ChangeStatus(double barcode) {
            return base.Channel.ChangeStatus(barcode);
        }
        
        public System.Threading.Tasks.Task<int> ChangeStatusAsync(double barcode) {
            return base.Channel.ChangeStatusAsync(barcode);
        }
    }
}
