//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DedicatedClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SenderResource", Namespace="http://schemas.datacontract.org/2004/07/DeliveryServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class SenderResource : DedicatedClient.ServiceReference1.PersonResource {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDInDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDInDB {
            get {
                return this.IDInDBField;
            }
            set {
                if ((this.IDInDBField.Equals(value) != true)) {
                    this.IDInDBField = value;
                    this.RaisePropertyChanged("IDInDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonResource", Namespace="http://schemas.datacontract.org/2004/07/DeliveryServiceLibrary")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DedicatedClient.ServiceReference1.ApplicationResource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DedicatedClient.ServiceReference1.SenderResource))]
    public partial class PersonResource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CprField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpr {
            get {
                return this.CprField;
            }
            set {
                if ((object.ReferenceEquals(this.CprField, value) != true)) {
                    this.CprField = value;
                    this.RaisePropertyChanged("Cpr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationResource", Namespace="http://schemas.datacontract.org/2004/07/DeliveryServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ApplicationResource : DedicatedClient.ServiceReference1.PersonResource {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPicturePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YellowCardPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVPath {
            get {
                return this.CVPathField;
            }
            set {
                if ((object.ReferenceEquals(this.CVPathField, value) != true)) {
                    this.CVPathField = value;
                    this.RaisePropertyChanged("CVPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuidLine {
            get {
                return this.GuidLineField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidLineField, value) != true)) {
                    this.GuidLineField = value;
                    this.RaisePropertyChanged("GuidLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPicturePath {
            get {
                return this.IDPicturePathField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPicturePathField, value) != true)) {
                    this.IDPicturePathField = value;
                    this.RaisePropertyChanged("IDPicturePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YellowCardPath {
            get {
                return this.YellowCardPathField;
            }
            set {
                if ((object.ReferenceEquals(this.YellowCardPathField, value) != true)) {
                    this.YellowCardPathField = value;
                    this.RaisePropertyChanged("YellowCardPath");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAllUsers", ReplyAction="http://tempuri.org/IAdminService/GetAllUsersResponse")]
        DedicatedClient.ServiceReference1.SenderResource[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAllUsers", ReplyAction="http://tempuri.org/IAdminService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<DedicatedClient.ServiceReference1.SenderResource[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAllApplications", ReplyAction="http://tempuri.org/IAdminService/GetAllApplicationsResponse")]
        DedicatedClient.ServiceReference1.ApplicationResource[] GetAllApplications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAllApplications", ReplyAction="http://tempuri.org/IAdminService/GetAllApplicationsResponse")]
        System.Threading.Tasks.Task<DedicatedClient.ServiceReference1.ApplicationResource[]> GetAllApplicationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteApplication", ReplyAction="http://tempuri.org/IAdminService/DeleteApplicationResponse")]
        int DeleteApplication(DedicatedClient.ServiceReference1.ApplicationResource application, bool deletePerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteApplication", ReplyAction="http://tempuri.org/IAdminService/DeleteApplicationResponse")]
        System.Threading.Tasks.Task<int> DeleteApplicationAsync(DedicatedClient.ServiceReference1.ApplicationResource application, bool deletePerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddCourier", ReplyAction="http://tempuri.org/IAdminService/AddCourierResponse")]
        int AddCourier(DedicatedClient.ServiceReference1.SenderResource courier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddCourier", ReplyAction="http://tempuri.org/IAdminService/AddCourierResponse")]
        System.Threading.Tasks.Task<int> AddCourierAsync(DedicatedClient.ServiceReference1.SenderResource courier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : DedicatedClient.ServiceReference1.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<DedicatedClient.ServiceReference1.IAdminService>, DedicatedClient.ServiceReference1.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DedicatedClient.ServiceReference1.SenderResource[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<DedicatedClient.ServiceReference1.SenderResource[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public DedicatedClient.ServiceReference1.ApplicationResource[] GetAllApplications() {
            return base.Channel.GetAllApplications();
        }
        
        public System.Threading.Tasks.Task<DedicatedClient.ServiceReference1.ApplicationResource[]> GetAllApplicationsAsync() {
            return base.Channel.GetAllApplicationsAsync();
        }
        
        public int DeleteApplication(DedicatedClient.ServiceReference1.ApplicationResource application, bool deletePerson) {
            return base.Channel.DeleteApplication(application, deletePerson);
        }
        
        public System.Threading.Tasks.Task<int> DeleteApplicationAsync(DedicatedClient.ServiceReference1.ApplicationResource application, bool deletePerson) {
            return base.Channel.DeleteApplicationAsync(application, deletePerson);
        }
        
        public int AddCourier(DedicatedClient.ServiceReference1.SenderResource courier) {
            return base.Channel.AddCourier(courier);
        }
        
        public System.Threading.Tasks.Task<int> AddCourierAsync(DedicatedClient.ServiceReference1.SenderResource courier) {
            return base.Channel.AddCourierAsync(courier);
        }
    }
}
